# Generated by Django 5.1.1 on 2024-09-15 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementry',
            name='kategories',
            field=models.CharField(default='Sneakers', max_length=255),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='rarity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
