# Generated by Django 5.1.1 on 2024-10-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementry',
            name='image_url',
            field=models.URLField(max_length=2038),
        ),
    ]
