# Generated by Django 5.1.1 on 2024-09-17 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_itementry_kategories_alter_itementry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
